# Generated by Django 3.2.4 on 2021-07-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(help_text='Телефон пользоавтеля', max_length=50)),
                ('last_visit_at', models.DateTimeField(help_text='Врея последнего визита.', max_length=40)),
            ],
        ),
    ]
