# Generated by Django 3.2.4 on 2021-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0002_alter_ttlockuser_last_visit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttlockuser',
            name='last_visit_at',
            field=models.CharField(help_text='Врея последнего визита.', max_length=13, null=True),
        ),
    ]
