# Generated by Django 3.2.4 on 2021-07-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0003_alter_ttlockuser_last_visit_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttlockuser',
            name='last_visit_at',
        ),
        migrations.RemoveField(
            model_name='ttlockuser',
            name='user_number',
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='keyboardPwd',
            field=models.CharField(default=1, max_length=14, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='lockDate',
            field=models.CharField(default=1, max_length=14, verbose_name='Время последнего визита.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='lockId',
            field=models.PositiveIntegerField(default=11, verbose_name='Номер замка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='recordType',
            field=models.CharField(default=1, max_length=14, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='success',
            field=models.PositiveIntegerField(default=1, max_length=3, verbose_name='Статус открытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlockuser',
            name='username',
            field=models.CharField(default=1, max_length=14, verbose_name='Имя/Номер пользователя'),
            preserve_default=False,
        ),
    ]
