# Generated by Django 3.2.4 on 2021-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0004_auto_20210708_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlockuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Номер телефона'),
        ),
    ]
