# Generated by Django 3.1.6 on 2021-08-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0006_auto_20210804_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ttlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockId', models.PositiveIntegerField(verbose_name='Номер замка')),
                ('address', models.CharField(max_length=40, verbose_name='Имя/Номер пользователя')),
            ],
        ),
        migrations.AlterField(
            model_name='ttlockuser',
            name='lockId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttlock.ttlock', verbose_name='Номер замка'),
        ),
    ]
