# Generated by Django 3.1.6 on 2021-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0007_auto_20210804_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlock',
            name='clientId',
            field=models.CharField(default=1, max_length=35, verbose_name='Номер клиета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttlock',
            name='token',
            field=models.CharField(default=1, max_length=35, verbose_name='Токен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ttlockuser',
            name='success',
            field=models.PositiveIntegerField(verbose_name='Статус открытия'),
        ),
    ]
