# Generated by Django 3.1.6 on 2021-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlock',
            name='client_secret',
            field=models.CharField(default=1, max_length=35, verbose_name='Секрет'),
            preserve_default=False,
        ),
    ]
