# Generated by Django 3.1.6 on 2021-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0012_ttlock_client_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttlock',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='ttlock',
            name='refresh_token',
            field=models.CharField(default=1, max_length=35, verbose_name='Токен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ttlock',
            name='address',
            field=models.CharField(max_length=40, verbose_name='Адрес'),
        ),
    ]
