# Generated by Django 3.1.6 on 2021-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0013_auto_20210805_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttlockuser',
            name='lockDate',
            field=models.CharField(max_length=14, null=True, verbose_name='Время последнего визита.'),
        ),
        migrations.AlterField(
            model_name='ttlockuser',
            name='recordType',
            field=models.CharField(max_length=14, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ttlockuser',
            name='success',
            field=models.PositiveIntegerField(null=True, verbose_name='Статус открытия'),
        ),
    ]
