# Generated by Django 3.2.6 on 2021-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlock', '0015_auto_20210805_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttlock',
            name='access_token',
            field=models.CharField(max_length=35, verbose_name='Аксес токен'),
        ),
        migrations.AlterField(
            model_name='ttlock',
            name='refresh_token',
            field=models.CharField(max_length=35, verbose_name='Рефреш окен'),
        ),
    ]
